export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE';
export const USER_FOLLOWING_STATE_CHANGE = 'USER_FOLLOWING_STATE_CHANGE';
export const USER_FOLLOWER_STATE_CHANGE = 'USER_FOLLOWER_STATE_CHANGE';